FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive

# apt install
RUN apt-get update && \
	apt-get install -y wget git

# install go
RUN wget https://dl.google.com/go/go1.14.3.linux-amd64.tar.gz && \
	tar -C /usr/local -xzf go1.14.3.linux-amd64.tar.gz

# git clone
RUN git clone https://github.com/i3h/ifconfig.git && \
	cd ifconfig && git checkout develop

# download assets
RUN wget https://github.com/i3h/ifconfig/releases/latest/download/ifconfig.tar.gz

# extract assets
RUN tar xzvf ifconfig.tar.gz && \
	cp -r dist ifconfig/dispatcher/static

# build
RUN cd ifconfig/dispatcher && /usr/local/go/bin/go build .

CMD cd ifconfig/dispatcher && \
	export IFCONFIG_DISPATCHER_PORT=3080 && \
	export IFCONFIG_API="http://api:3000" && \
	./dispatcher
