FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive
ARG GEOIP2GQL_PORT=3001

# apt install
RUN apt-get update && \
	apt-get install -y wget git npm

# git clone
RUN git clone https://github.com/maxmind/MaxMind-DB.git && \
	git clone https://github.com/i3h/geoip2-gql.git

# add maxmind mmdb
RUN mkdir geoip2-gql/maxmind && \
	cp MaxMind-DB/test-data/GeoIP2-Anonymous-IP-Test.mmdb \
	geoip2-gql/maxmind/GeoIP2-Anonymous-IP.mmdb && \
	cp MaxMind-DB/test-data/GeoIP2-City-Test.mmdb \
	geoip2-gql/maxmind/GeoIP2-City.mmdb && \
	cp MaxMind-DB/test-data/GeoIP2-Connection-Type-Test.mmdb \
	geoip2-gql/maxmind/GeoIP2-Connection-Type.mmdb && \
	cp MaxMind-DB/test-data/GeoIP2-Country-Test.mmdb \
	geoip2-gql/maxmind/GeoIP2-Country.mmdb && \
	cp MaxMind-DB/test-data/GeoIP2-Domain-Test.mmdb \
	geoip2-gql/maxmind/GeoIP2-Domain.mmdb && \
	cp MaxMind-DB/test-data/GeoIP2-Enterprise-Test.mmdb \
	geoip2-gql/maxmind/GeoIP2-Enterprise.mmdb && \
	cp MaxMind-DB/test-data/GeoIP2-ISP-Test.mmdb \
	geoip2-gql/maxmind/GeoIP2-ISP.mmdb && \
	cp MaxMind-DB/test-data/GeoLite2-ASN-Test.mmdb \
	geoip2-gql/maxmind/GeoLite2-ASN.mmdb

# install go
RUN wget https://dl.google.com/go/go1.14.3.linux-amd64.tar.gz && \
	tar -C /usr/local -xzf go1.14.3.linux-amd64.tar.gz

# build
RUN cd geoip2-gql && /usr/local/go/bin/go build .

CMD cd geoip2-gql && export GEOIP2GQL_PORT=3001 && ./geoip2-gql
